# Question 1

In [1]:
import numpy as np
arr=np.arange(2,50,3)
print(arr)

[ 2  5  8 11 14 17 20 23 26 29 32 35 38 41 44 47]


# Question 2

In [11]:
l1=[]
l2=[]
for i  in range(5):
    l1.append(int(input()))
for i in range(5):
    l2.append(int(input()))
a=np.array(l1)
b=np.array(l2)
narr=np.sort(np.concatenate((a,b)))
print(narr)

1
2
3
4
5
6
7
8
9
0
[0 1 2 3 4 5 6 7 8 9]


# Question 3

In [19]:
arr=np.array([[12,13,34,54],[1,5,6,7]])
print(np.ndim(arr))
print(np.size(arr))

2
8


# Question 4

In [28]:
arr=np.array([2,3,4,5,6,7])
a1=np.expand_dims(arr,axis=1)
print(a1)
print(np.ndim(a1))
print(arr)
a2=arr[:, np.newaxis]
print(a2)

[[2]
 [3]
 [4]
 [5]
 [6]
 [7]]
2
[2 3 4 5 6 7]
[[2]
 [3]
 [4]
 [5]
 [6]
 [7]]


# Question 5

In [33]:
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
print(np.hstack((arr1,arr2)))
print(np.vstack((arr1,arr2)))

[1 2 3 4 5 6]
[[1 2 3]
 [4 5 6]]


# Question 6

In [34]:
arr=np.array([1,2,4,5,2,6,4,8,3,6,9,2])
print(np.unique(arr,return_counts=True))

(array([1, 2, 3, 4, 5, 6, 8, 9]), array([1, 3, 1, 2, 1, 2, 1, 1], dtype=int64))
